{{- if .Values.cassandraPrometheusScrap }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cassandra-{{ .Release.Namespace }}
  namespace: observability
  labels:
    app: cassandra
    prometheus: observability
spec:
  selector:
    matchLabels:
      app: cassandra
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: 60s
{{- end }}