{{- if .Values.cassandraExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cassandra-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: cassandra-exporter
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: {{ .Values.cassandraExporter.config.listenPort }}
      protocol: TCP
    - name: jmx
      port: 5555
      targetPort: 5555
  selector:
    app: cassandra-exporter
{{- end }}