# Set where Cassandra local data should be located
cassandraNodeSelector:
  node-role.kubernetes.io/node: "true"

# Update deployed date to force a rolling upgrade
cassandraDeployedDate: ""

# Number of nodes
cassandraReplicaCount: 3
# Number of maximum dead nodes
cassandraMaxUnavailableNodes: 1

# Cassandra settings
cassandraImageName: "quay.io/mysocialapp/cassandra"
cassandraImageVersion: "3.11.1-2"
cassandraMaxHeap: 4G
cassandraHeapNewSize: 256M
cassandraDC: "DC1"